In [93]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [94]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder


# load dataset

In [95]:
datapath = '/content/drive/MyDrive/ml_code/nlp/amazon review analysis/Reviews.csv'


df = pd.read_csv(datapath)


# **understanding data**

In [96]:
df.head(10)

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
5   6  B006K2ZZ7K   ADT0SRK1MGOEU                   Twoapennything   
6   7  B006K2ZZ7K  A1SP2KVKFXXRU1                David C. Sullivan   
7   8  B006K2ZZ7K  A3JRGQVEQN31IQ               Pamela G. Williams   
8   9  B000E7L2R4  A1MZYO9TZK0BBI                         R. James   
9  10  B00171APVA  A21BT40VZCCYT4                    Carol A. Reed   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   
5                     0                       0      4  1342051200   
6                     0                       0      5  1340150400   
7                     0                       0      5  1336003200   
8                     1                       1      5  1322006400   
9                     0                       0      5  1351209600   

                                         Summary  \
0                          Good Quality Dog Food   
1                              Not as Advertised   
2                          "Delight" says it all   
3                                 Cough Medicine   
4                                    Great taffy   
5                                     Nice Taffy   
6  Great!  Just as good as the expensive brands!   
7                         Wonderful, tasty taffy   
8                                     Yay Barley   
9                               Healthy Dog Food   

                                                Text  
0  I have bought several of the Vitality canned d...  
1  Product arrived labeled as Jumbo Salted Peanut...  
2  This is a confection that has been around a fe...  
3  If you are looking for the secret ingredient i...  
4  Great taffy at a great price.  There was a wid...  
5  I got a wild hair for taffy and ordered this f...  
6  This saltwater taffy had great flavors and was...  
7  This taffy is so good.  It is very soft and ch...  
8  Right now I'm mostly just sprouting this so my...  
9  This is a very healthy dog food. Good for thei...

In [97]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype 
---  ------                  --------------   ----- 
 0   Id                      568454 non-null  int64 
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64 
 5   HelpfulnessDenominator  568454 non-null  int64 
 6   Score                   568454 non-null  int64 
 7   Time                    568454 non-null  int64 
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB
None


In [87]:
df.drop(columns = ["ProductId","UserId","ProfileName","Time"] , inplace = True)

In [88]:
# df=df.head(10000)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Id                      10000 non-null  int64 
 1   HelpfulnessNumerator    10000 non-null  int64 
 2   HelpfulnessDenominator  10000 non-null  int64 
 3   Score                   10000 non-null  int64 
 4   Summary                 10000 non-null  object
 5   Text                    10000 non-null  object
dtypes: int64(4), object(2)
memory usage: 468.9+ KB


# handeling missing data

In [98]:
max_non_null_val = df["Id"].count()
print("Percentage of missing values in each column:\n")
missing_percent = []
for col in df.columns:
  missing_percent.append(df[col].isnull().sum()/max_non_null_val*100)
  print(f"{col} : {df[col].isnull().sum()/max_non_null_val*100}%")

Percentage of missing values in each column:

Id : 0.0%
ProductId : 0.0%
UserId : 0.0%
ProfileName : 0.004573808962554577%
HelpfulnessNumerator : 0.0%
HelpfulnessDenominator : 0.0%
Score : 0.0%
Time : 0.0%
Summary : 0.0047497246918836%
Text : 0.0%


In [99]:
df.dropna(inplace = True)
df.reset_index(drop=True, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568401 entries, 0 to 568400
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype 
---  ------                  --------------   ----- 
 0   Id                      568401 non-null  int64 
 1   ProductId               568401 non-null  object
 2   UserId                  568401 non-null  object
 3   ProfileName             568401 non-null  object
 4   HelpfulnessNumerator    568401 non-null  int64 
 5   HelpfulnessDenominator  568401 non-null  int64 
 6   Score                   568401 non-null  int64 
 7   Time                    568401 non-null  int64 
 8   Summary                 568401 non-null  object
 9   Text                    568401 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB


#Making the count of reviews same

In [101]:
value_counts = df['Score'].value_counts()
min_count = value_counts.min()

df = df.groupby('Score').apply(lambda x: x.sample(min_count)).reset_index(drop=True)
df['Score'].value_counts()


Score
1    29743
2    29743
3    29743
4    29743
5    29743
Name: count, dtype: int64

#VADER method

In [115]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [116]:
summary_list = []
review_list = []
for i in range(df['Text'].count()):
    summary_score = sia.polarity_scores(df.iloc[i]["Summary"])
    review_score = sia.polarity_scores(df.iloc[i]["Text"])

    summary_list.append(summary_score)
    review_list.append(review_score)

print(summary_list[1], review_list[1])

KeyboardInterrupt: 

In [ ]:
summary_list_df = pd.DataFrame(summary_list)
review_list_df  = pd.DataFrame(review_list)

In [ ]:
review_list_df.columns = ["rev_neg","rev_neu","rev_pos","rev_compound"]
review_list_df.info()

In [ ]:
summary_list_df.columns = ["summ_neg","summ_neu","summ_pos","summ_compound"]
summary_list_df.head()

In [ ]:
df = pd.concat([df, review_list_df, summary_list_df], axis =1 )

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99998 entries, 0 to 99997
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Id                      99998 non-null  int64  
 1   HelpfulnessNumerator    99998 non-null  int64  
 2   HelpfulnessDenominator  99998 non-null  int64  
 3   Score                   99998 non-null  int64  
 4   Summary                 99998 non-null  object 
 5   Text                    99998 non-null  object 
 6   rev_neg                 99998 non-null  float64
 7   rev_neu                 99998 non-null  float64
 8   rev_pos                 99998 non-null  float64
 9   rev_compound            99998 non-null  float64
 10  summ_neg                99998 non-null  float64
 11  summ_neu                99998 non-null  float64
 12  summ_pos                99998 non-null  float64
 13  summ_compound           99998 non-null  float64
dtypes: float64(8), int64(4), object(2)
mem

In [117]:
for col in df:
  print(col," : ", df[col].isnull().sum())


Id  :  0
HelpfulnessNumerator  :  0
HelpfulnessDenominator  :  0
Score  :  0
Summary  :  0
Text  :  0
rev_neg  :  0
rev_neu  :  0
rev_pos  :  0
rev_compound  :  0
summ_neg  :  0
summ_neu  :  0
summ_pos  :  0
summ_compound  :  0


In [119]:
df_X = df.drop(columns = ["Text","Id","Summary","Score"])
y= df["Score"]

In [120]:
for col in df_X:
  print(col," : ", df_X[col].isnull().sum())


HelpfulnessNumerator  :  0
HelpfulnessDenominator  :  0
rev_neg  :  0
rev_neu  :  0
rev_pos  :  0
rev_compound  :  0
summ_neg  :  0
summ_neu  :  0
summ_pos  :  0
summ_compound  :  0


In [121]:
df_X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99998 entries, 0 to 99997
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   HelpfulnessNumerator    99998 non-null  int64  
 1   HelpfulnessDenominator  99998 non-null  int64  
 2   rev_neg                 99998 non-null  float64
 3   rev_neu                 99998 non-null  float64
 4   rev_pos                 99998 non-null  float64
 5   rev_compound            99998 non-null  float64
 6   summ_neg                99998 non-null  float64
 7   summ_neu                99998 non-null  float64
 8   summ_pos                99998 non-null  float64
 9   summ_compound           99998 non-null  float64
dtypes: float64(8), int64(2)
memory usage: 7.6 MB


## Splitting data into training and testing datasets

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size = 0.20, random_state = 0)

##Scaling the data

In [124]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [125]:
(X_train).shape()

(array([], dtype=int64), array([], dtype=int64))

##Trainnig Logistic regression model



In [126]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear',random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [127]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1115     0    11     0   684]
 [  465     0     5     0   653]
 [  321     0    15     0  1302]
 [  112     0     3     0  2857]
 [  242     0     7     0 12208]]


0.6669

##Training a knn model




In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

##XG boost model

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

##Training a random forest model

In [128]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [129]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1138   123    83    48   418]
 [  336   251    92    62   382]
 [  195    85   474   158   726]
 [  103    35   119   728  1987]
 [  241    85   168   465 11498]]


0.70445

## Training naive bayes model

In [ ]:
from sklearn.naive_bayes import Multinomial_NB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

In [131]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1233    20   138    69   350]
 [  570    29    98    65   361]
 [  473    45   156   110   854]
 [  234    27   155   168  2388]
 [  522    47   399   355 11134]]


0.636

#Loading the Spacy model


In [102]:
!pip install spacy
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [103]:
import spacy
nlp = spacy.load("en_core_web_lg")

##preprocessing the data

In [104]:
df["Text"] = df["Text"] + " " + df["Summary"]

In [ ]:
corpus = []
for i in range(0, df["Text"].count()):
    review = df['Text'][i]
    doc = nlp(review)
    tokens = [token.lemma_.lower() for token in doc if not token.is_stop and token.is_alpha]
    review = ' '.join(tokens)
    corpus.append(review)

# Creating bag of words model

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5500)
X = cv.fit_transform(corpus).toarray()
y = df["Score"].values
y = y-1

## Splitting data into training and testing datasets

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

##Scaling the data

In [52]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Training naive bayes model

In [53]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  6   0   2   2  11]
 [  1   0   0   1   8]
 [  0   1   0   1   9]
 [  1   0   0   3  24]
 [  3   0   1   6 120]]


0.645

##Training Logistic regression model



In [55]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear',random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  7   1   0   3  10]
 [  1   1   0   1   7]
 [  1   0   0   2   8]
 [  0   0   2   6  20]
 [  1   0   2   9 118]]


0.66

##XG boost model

In [57]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  3   2   3   1  12]
 [  1   0   1   2   6]
 [  1   0   1   1   8]
 [  2   1   1   3  21]
 [  0   1   3   6 120]]


0.635


##Training a random forest model

In [59]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  1   0   0   0  20]
 [  0   0   0   0  10]
 [  0   0   0   0  11]
 [  0   0   0   0  28]
 [  1   0   0   1 128]]


0.645

# Creating n-gram bag of words model

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (1,2))
X = cv.fit_transform(corpus).toarray()
y = df["Score"].values
y = y-1

## Splitting data into training and testing datasets

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0, stratify = df["Score"])

##Scaling the data

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Training naive bayes model

In [23]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 7  0  1  7  5]
 [ 3  0  1  4  1]
 [ 3  1  1  6  4]
 [ 4  0  1  9 14]
 [ 5  0  5 20 98]]


0.575

##Training Logistic regression model



In [25]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear',random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  2   0   0   1  17]
 [  0   0   0   0   9]
 [  0   0   0   0  15]
 [  1   0   0   0  27]
 [  0   0   0   0 128]]


0.65

##XG boost model

In [27]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  7   0   0   2  11]
 [  1   1   0   0   7]
 [  3   0   1   0  11]
 [  2   1   2   2  21]
 [  1   4   1   4 118]]


0.645


##Training a random forest model

In [31]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  1   0   0   0  19]
 [  0   0   0   0   9]
 [  0   0   0   0  15]
 [  0   0   0   0  28]
 [  0   0   0   0 128]]


0.645

# Creating TF-IDF model

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()
X = tv.fit_transform(corpus).toarray()
y = df["Score"].values
y = y-1

## Splitting data into training and testing datasets

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0, stratify = df["Score"])

##Scaling the data

In [36]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Training naive bayes model

In [37]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  3   0   1  12   4]
 [  2   0   0   2   5]
 [  1   1   1   3   9]
 [  0   1   0   7  20]
 [  0   0   0  28 100]]


0.555

##Training Logistic regression model



In [39]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear',random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   0   0   0  20]
 [  0   0   0   0   9]
 [  0   0   0   0  15]
 [  0   0   0   0  28]
 [  0   0   0   0 128]]


0.64

##XG boost model

In [41]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   3   0   0  17]
 [  0   1   0   1   7]
 [  0   1   0   1  13]
 [  0   0   0   0  28]
 [  0   0   0   0 128]]


0.645


##Training a random forest model

In [43]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   0   0   0  20]
 [  0   0   0   0   9]
 [  0   0   0   0  15]
 [  0   0   0   0  28]
 [  0   0   0   0 128]]


0.64

# Creating word vectors model

In [ ]:
X=[]
for i in corpus:
  X.append(nlp(i).vector)

In [ ]:
y = df["Score"].values
y = y-1

## Splitting data into training and testing datasets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0, stratify = df["Score"])

##Scaling the data

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Training naive bayes model

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

##Training Logistic regression model



In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear',random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

##XG boost model

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


##Training a random forest model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

# Creating Gensim model trained on google news dataset

In [ ]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
X=[]
for i in corpus:
  X.append(wv.get_mean_vector(i))

y = df["Score"].values
y = y-1

## Splitting data into training and testing datasets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0, stratify = df["Score"])

##Scaling the data

In [ ]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Training naive bayes model

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  3   0   1  12   4]
 [  2   0   0   2   5]
 [  1   1   1   3   9]
 [  0   1   0   7  20]
 [  0   0   0  28 100]]


0.555

##Training Logistic regression model



In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear',random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   0   0   0  20]
 [  0   0   0   0   9]
 [  0   0   0   0  15]
 [  0   0   0   0  28]
 [  0   0   0   0 128]]


0.64

##XG boost model

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   3   0   0  17]
 [  0   1   0   1   7]
 [  0   1   0   1  13]
 [  0   0   0   0  28]
 [  0   0   0   0 128]]


0.645


##Training a random forest model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   0   0   0  20]
 [  0   0   0   0   9]
 [  0   0   0   0  15]
 [  0   0   0   0  28]
 [  0   0   0   0 128]]


0.64